### ISSUE TITLE
Problem in selecting WIFI networks

### ISSUE THREAD

**Issue by manu69x** [OctoPrint/OctoPrint-Netconnectd#3]
Hello
I'm testing this plugin in Octopi
with Octoprint 1.2.
I'm able to install all and I see the WIFI network list in the WEB interface, ... but
if I try to select one SSID WIFI and then I reboot, i recive a dhcpcd error
and I have no networks at all, until i edit 
sudo nano /etc/network/interfaces
and remove dhcp for manual
Any help for this ?

**Comment by foosel** [comment]
That would better suited at the netconnectd bug tracker, but that being said, this was written before that new fangled dhcpcd thingy started shipping with raspbian. It doesn't need it to operate and the dhcpcd error should be ignored if I remember correctly since the standard network setup will just take over usually, but I suggest to disable dhcpcd instead, there's really no need or advantage to it when networking is done from the command line properly. To be completely honest, I consider it an abomination, setting networks to "manual" to have them actually use dhcp is just plain wrong ;)

**Comment by manu69x** [comment]
thanks for the fast reply.
Can you tell me the link for report this kind of issue ?
.
So you suggest to uninstal dhcpcd ?

**Comment by foosel** [comment]
https://github.com/foosel/netconnectd and yes, but I'll take a look at what exactly to do tomorrow (it's 10pm here).

**Comment by foosel** [comment]
Closing because not an issue of the OctoPrint plugin but the service it talks to or rather the service it talks to depending on a proper network base configuration which the Tappan image from 15-5-5 doesn't provide anymore due to some non standard setup.

**Comment by manu69x** [comment]
I dont' know if can help but
finaly I was able to get Octopi working with Netconnectd and WIFI

Prerequisite for this is: having WIFI dongle driver installed Netconnectd
installed and NetConnectd Plugin installed.

I have disabled dhcpcd with:

sudo update-rc.d -f dhcpcd remove

then modified /etc/network/interfaces

I have only this (no wlan0 and subst manual with dhcp)

auto lo
iface lo inet loopback

auto eth0
allow-hotplug eth0
iface eth0 inet dhcp

finaly for have wifi permanent I'v modified /etc/rc.local

sudo nano /etc/rc.local
and added

sudo netconnectcli select_wifi

just before the IP address print

et voilà
now I can select WIFI network in OctoPrint NetConnectd Plugin and this is
permanent after reboot :)

2015-06-28 22:15 GMT+02:00 Gina Häußge notifications@github.com:
